### PR TITLE
Build for Version v2016.1

### PR DESCRIPTION
**Pull request by CADbloke**
I copied the v10 `csproj`, updated Nugets & packaging `.bat` files.

Things I didn't do ...
- change the `103_PushPackages.bat` - it needs updating and I'm not the manager of that space.
- I didn't change ANY code so there may be dragons lurking within if the new Wave breaks anything

I tested it in VS2015.update 2 with R# 2016.1 RTM and it seems to work ok for me.

### CODE REVIEW

**Comment by CADbloke** [comment]
In case you're wondering how to install this locally if this pull request doesn't get merged or if this repo isn't updated by the owner, see https://www.jetbrains.com/help/resharper/sdk/Extensions/Deployment/LocalInstallation/InstallCustomSource.html - Add the `.........\ExceptionalReSharper\build\Packages` folder of your cloned the repo (including this pull request) to the Resharper Extension Manager sources. It should show up - sort them by newest.

Works on My Machine [TM]

**Comment by firehirsch** [comment]
Cloned it, build it, installed it, works.
I would appreciate it, if this Pullrequest gets pulled very soon.

**Comment by rsuter** [comment]
I will check and merge this PR today

**Comment by rsuter** [comment]
Maybe we should name the NuGet not `Exceptional.2016.1` but `Exceptional.Next` (or what else?), otherwise we will end up with lots of NuGets and lots of projects and maintaining all the projects will be very time consuming... Because RS is now licensed as a service, all users of 2016.1 will update to 2016.2 and we just have to support the newest version!?

**Comment by rsuter** [comment]
Ok new package is now available: https://resharper-plugins.jetbrains.com/packages/Exceptional.2016.1/
Can you test if it is working for you?
Are you interested to help develop the project? There are lots of open issues and I am currently working on other OSS projects...
Thanks for creating the PR...

**Comment by CADbloke** [comment]
@rsuter Thank you for creating Exceptional. I really missed it when I updated R# to v 2016.1. I originally just had a fiddle the with the VS Solution to see if it would build against the new SDK, when I got it to work I thought I should submit a PR just so others could use it too.

I'm not familiar with the code (I looked into the tests but not much else) and I presently don't have much spare time (I am within a couple of weeks of launching my first product - www.tvCAD.tv) but I will keep an eye on the project and revisit it when things calm down a bit.

Thanks again for Exceptional, I find it very useful. It was a pleasure to be able to help out. I hope I can help again in the future.

cheers
Ewen

**Pull request merged**
