### PR TITLE
R# SDK updated to 2019.3

### PR DESCRIPTION
**Pull request by ManticSic**
Resharper is not available for the new R# 2019.3.
I've updated referenced sdk and adjust the api usage.

ReSharper.Exceptional.Settings.ExceptionalOptionsPage is removed, because of the new api.
JetBrains.Application.UI.Options.OptionPages.AOptionsPpage has no longer the Control property.
Now the OptionsPage decorator and the IOptionsPage interface is directly on the UserControl.

### CODE REVIEW

**Comment by tkurskiev** [comment]
Cool! I'm using 2019.3 and was upset to find that there's no Exceptional Plugin listed in Extension Manager. Hope this will be merged soon.

**Comment by ManticSic** [comment]
> 
> 
> Cool! I'm using 2019.3 and was upset to find that there's no Exceptional Plugin listed in Extension Manager. Hope this will be merged soon.

I hope it will be published till next week. Until then you can build and deploy it localy

Instruction:
1. clone https://github.com/ManticSic/ExceptionalReSharper
1. open Developer Command Prompt for VS
1. navigate to the projects build directory (`cd path/to/the/project/build`)
1. run 00_RestorePackages.bat
1. run 01_Build.bat
1. run 02_CreatePackages.bat
1. In your R# Options, add a new packag reference (`ReSharper > Options > Extension Manager`) to `path/to/the/project/build/packages`
1. now version 0.20.0 should be available

**Comment by Mike-EEE** [comment]
Thank you for getting this done all. 👍

FWIW, please feel free to vote for this issue to improve the extension model experience so we don't have to continually nag extension model authors for each release:

https://youtrack.jetbrains.com/issue/RSRP-459966

**Comment by Mike-EEE** [comment]
Hello.. has this been deployed?  I tried installing it from Extensions Manager in ReSharper and it is not available. :(

**Comment by ManticSic** [comment]
Sadly not, but I will upload a new Plugin as a nightly build to the jetrains repository.

**Comment by RicoSuter** [comment]
@manticsic, you should now be able to upload new versions

**Pull request merged**
