### PR TITLE
Fixed issue #57, incorrect analysis for named arguments.

### PR DESCRIPTION
**Pull request by chris-dd**
Added playground file for testing named arguments.

### CODE REVIEW

**Comment by RSuter** [comment]
Shouldn't we use split and equals instead of endswith?

**Comment by chris-dd** [comment]
You are right, probably a Split(':').Last().Trim().Equals(...) would be best, to remove any whitespaces between the ':' and the parameter. I will try to do the changes tonight.

**Comment by chris-dd** [comment]
I adjusted the playground file to reflect a case where the old implementation would cause an issue. Fixed the evaluation to use split and equals.

**Comment by RSuter** [comment]
Thank you for the pr

**Comment by RSuter** [comment]
v0.11.0

**Pull request merged**
